language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: OrexgCpIjLYaX4VXCuJUahZVMNd7zlQ9RGQG5R01dtCPq1EFzO4pBCZrUP3kO9NTNbgP0syoRBmHDjc17cHr65irmogblVJw8wLHsVwEY7+JtrKogYv/tWJ324CE6rKlaZabrW7YOpT8l4sZ7BPrc5/4QDqxiMVaT8gb3xq4xasfwq9cGZzyJ+ViXpw/utm6J6MEov7XJP+of8eRHuetdeUam9q18UygXCYNyR8OiOuW9IBctDPD6uAvcK22bw1jMOHFMUsrBhweB6mWTY+ksFtWu/4AzK+w0uytdlfCAnpdm3CMUk6RBo6etaMM+Bu7O5yOLw8SZbycHk59bVz0s/Rvjsm65uwAkuBtAJIboxitTuvso+EY4DY1kVb+lDG9keXm/iioVNHDZU65xWNf/ZQKuBSSEhwQYE5oWW3uP5QakaxAAVoB32KOfU8z0bP5CkpAMJJ/kVY7jPKs9XmyuZ5A67RMP/TsPapsgHiJznZgFS7/HPx+3Q1piP7gS1+pcv7V/gjObMqQ4n/kOeWyJLU4eb5vldEbx0tvkIK3Xturzu639zFn1M1E/ob0elHRuOMuLedRCn0qWDo1iTa3CLA3I5Segl+O9zoJrd24v3KVxb9GNwMEK15n1ofyCMDf832ccBTI1UWkFBhWUkBTgRQdH/YkuN/25l2cjGN5QSQ=
  app: roots-interface
  skip_cleanup: true
