language: node_js
node_js:
  - "node"
notifications:
  email: false

deploy:
  provider: heroku
  api_key:   
    secure: process.env.REACT_APP_HEROKU_API_KEY
  app: roots-interface
  on:
    repo: roots-capstone/roots-interface